import "~/styles/globals.css";
import { TopNav } from "./_components/topnav";
import { ClerkProvider } from '@clerk/nextjs'
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Rugby App",
  description: "Generated by youtube & docs",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    
    <ClerkProvider>
      <html lang="en">
        <body className={`${GeistSans.variable}`}>
          <TopNav />
          <div className="container mx-auto px-4">{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}